import Foundation

@main
struct ClipboardCodecTests {
    static func main() {
        let h1 = ClipboardCodec.hash(text: "hello")
        let h2 = ClipboardCodec.hash(text: "hello")
        let h3 = ClipboardCodec.hash(text: "world")
        expect(h1 == h2, "same text same hash")
        expect(h1 != h3, "diff text diff hash")
        expect(h1.count == 64, "hash is sha256 hex")
        expect(ClipboardCodec.shouldSkip(typeIdentifiers: ["org.nspasteboard.ConcealedType", "public.utf8-plain-text"]), "concealed skipped")
        expect(ClipboardCodec.shouldSkip(typeIdentifiers: ["org.nspasteboard.TransientType"]), "transient skipped")
        expect(ClipboardCodec.shouldSkip(typeIdentifiers: ["org.nspasteboard.AutoGeneratedType"]), "autogenerated skipped")
        expect(!ClipboardCodec.shouldSkip(typeIdentifiers: ["public.utf8-plain-text"]), "plain text not skipped")
        print("ALL PASS")
    }
    static func expect(_ c: Bool, _ m: String) {
        if !c { FileHandle.standardError.write(Data("FAIL: \(m)\n".utf8)); exit(1) }
    }
}
