// swiftc -o /tmp/relnotes EasySign/Core/Update/ReleaseNotes.swift Tests/ReleaseNotesTests.swift && /tmp/relnotes
//
// ReleaseNotesParser 是纯逻辑(不引用 MobileDevice / SwiftUI),可独立编译测试。
// 预期输出以 ALL PASS 结尾。

import Foundation

@main
struct ReleaseNotesTests {
    static var failures = 0

    static func check(_ condition: Bool, _ label: String) {
        if condition {
            print("  ok   \(label)")
        } else {
            failures += 1
            print("  FAIL \(label)")
        }
    }

    static func main() {
        autoGeneratedRelease()
        changelogVariants()
        realContent()
        edgeCases()
        print(failures == 0 ? "\nALL PASS" : "\n\(failures) FAILURE(S)")
        exit(failures == 0 ? 0 : 1)
    }

    /// 真实样本:自动生成的 release,正文只有一行 Full Changelog。
    static func autoGeneratedRelease() {
        let body = "**Full Changelog**: https://github.com/crazyball666/EasySign/compare/v1.3.1...v1.3.2"
        let notes = ReleaseNotesParser.parse(body)
        check(notes.hasNoDescription, "只有 Full Changelog 时视为无说明")
        check(notes.blocks.isEmpty, "该行不进正文")
        check(notes.fullChangelogURL?.absoluteString
                == "https://github.com/crazyball666/EasySign/compare/v1.3.1...v1.3.2",
              "提取出 compare 链接")
    }

    static func changelogVariants() {
        let plain = ReleaseNotesParser.parse("full changelog: https://example.com/compare/a...b")
        check(plain.fullChangelogURL?.absoluteString == "https://example.com/compare/a...b",
              "大小写不敏感 + 无 ** 包裹")

        let linked = ReleaseNotesParser.parse("**Full Changelog**: [v1..v2](https://example.com/c)")
        check(linked.fullChangelogURL?.absoluteString == "https://example.com/c",
              "Markdown 链接形式取 URL 而非显示文本")
    }

    static func realContent() {
        let body = """
        ## 新增
        - 设备工具支持真实 App 图标
        * 应用详情弹窗

        修正了签名类型判定。

        ---
        **Full Changelog**: https://example.com/compare/x...y
        """
        let notes = ReleaseNotesParser.parse(body)
        check(!notes.hasNoDescription, "有内容时不算空")
        check(notes.blocks == [
            .heading("新增"),
            .bullet("设备工具支持真实 App 图标"),
            .bullet("应用详情弹窗"),
            .paragraph("修正了签名类型判定。"),
        ], "标题/条目/段落切分正确,分隔线与 changelog 行被剔除")
        check(notes.fullChangelogURL != nil, "有正文时仍提取 changelog 链接")
    }

    static func edgeCases() {
        let empty = ReleaseNotesParser.parse("")
        check(empty.hasNoDescription && empty.fullChangelogURL == nil, "空正文")

        let blank = ReleaseNotesParser.parse("   \n\n  \n")
        check(blank.hasNoDescription, "只有空白行")

        let headings = ReleaseNotesParser.parse("### 修复\n#### 细节")
        check(headings.blocks == [.heading("修复"), .heading("细节")], "多级标题的 # 全部剥掉")

        // 正文里出现 "Full Changelog" 但不是那一行的格式,不应被吞掉
        let mention = ReleaseNotesParser.parse("- 重写了 Full Changelog 的展示")
        check(mention.blocks == [.bullet("重写了 Full Changelog 的展示")], "非行首的同名文本不误伤")
        check(mention.fullChangelogURL == nil, "未误提取链接")
    }
}
