import Foundation
import CryptoKit

/// 剪贴板纯逻辑:内容哈希(回环防护)+ 机密/临时跳过判定。
enum ClipboardCodec {
    static let skipTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]
    static func hash(text: String) -> String {
        SHA256.hash(data: Data(text.utf8)).map { String(format: "%02x", $0) }.joined()
    }
    static func shouldSkip(typeIdentifiers: [String]) -> Bool {
        !skipTypes.isDisjoint(with: Set(typeIdentifiers))
    }
}
